<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsGameModule>false</IsGameModule>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>$(ReferenceRoot)/TaleWorlds.CampaignSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
