using System;
using System.Linq;
using System.Reflection;
using Retinues.Utilities;

namespace Retinues.Configuration
{
    public static partial class SettingsManager
    {
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ //
        //                      Internal wiring                   //
        // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ //

        /// <summary>
        /// Discovers all static IOption fields in the Settings class via reflection.
        /// </summary>
        internal static void DiscoverOptions()
        {
            if (_discovered)
                return;

            try
            {
                Type settingsType = typeof(Settings); // <== renamed class
                FieldInfo[] fields = settingsType.GetFields(
                    BindingFlags.Public | BindingFlags.Static
                );

                int ordinal = 0;

                foreach (FieldInfo f in fields.OrderBy(fi => fi.MetadataToken))
                {
                    // Sections first: used to define ordering.
                    if (typeof(Section).IsAssignableFrom(f.FieldType))
                    {
                        if (f.GetValue(null) is not Section section)
                            continue;

                        section.Ordinal = _sections.Count;
                        _sections.Add(section);

                        string sectionName = section.Name;
                        if (
                            !string.IsNullOrWhiteSpace(sectionName)
                            && !_sectionOrdinalByName.ContainsKey(sectionName)
                        )
                        {
                            _sectionOrdinalByName[sectionName] = section.Ordinal;
                        }

                        continue;
                    }

                    // Options
                    if (!typeof(IOption).IsAssignableFrom(f.FieldType))
                        continue;

                    object raw = f.GetValue(null);
                    if (raw == null)
                        continue;

                    IOption opt = (IOption)raw;

                    // Autogenerated key from field name.
                    string key = f.Name;
                    opt.Key = key;

                    _all.Add(opt);
                    _byKey[key] = opt;
                    _ordinalByKey[key] = ordinal++;
                    _values[key] = opt.Default;

                    Type optType = opt.GetType();
                    PropertyInfo getterProp = optType.GetProperty(
                        "Getter",
                        BindingFlags.Instance | BindingFlags.NonPublic
                    );
                    PropertyInfo setterProp = optType.GetProperty(
                        "Setter",
                        BindingFlags.Instance | BindingFlags.NonPublic
                    );
                    if (getterProp == null || setterProp == null)
                        continue;

                    Type valueType = opt.Type;
                    MethodInfo makeGetterMethod = typeof(SettingsManager)
                        .GetMethod("MakeGetter", BindingFlags.NonPublic | BindingFlags.Static)
                        .MakeGenericMethod(valueType);
                    MethodInfo makeSetterMethod = typeof(SettingsManager)
                        .GetMethod("MakeSetter", BindingFlags.NonPublic | BindingFlags.Static)
                        .MakeGenericMethod(valueType);

                    object getterDelegate = makeGetterMethod.Invoke(null, new object[] { key });
                    object setterDelegate = makeSetterMethod.Invoke(null, new object[] { key });

                    getterProp.SetValue(opt, getterDelegate, null);
                    setterProp.SetValue(opt, setterDelegate, null);
                }

                _discovered = true;
            }
            catch (Exception e)
            {
                Log.Exception(e, "DiscoverOptions failed.");
            }
        }

        /// <summary>
        /// Gets the ordinal of a section by name.
        /// </summary>
        internal static int GetSectionOrdinal(string sectionName)
        {
            if (_sectionOrdinalByName.TryGetValue(sectionName, out int ordinal))
                return ordinal;
            return int.MaxValue;
        }

        /// <summary>
        /// Gets the ordinal of an option by key.
        /// </summary>
        internal static int GetOrdinal(string key)
        {
            if (_ordinalByKey.TryGetValue(key, out int idx))
                return idx;
            return int.MaxValue;
        }
    }
}
